// <auto-generated />
#nullable disable

using System;
using Golden.Publication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Golden.Publication.Data.Migrations;

[DbContext(typeof(PublicationDbContext))]
partial class PublicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Golden.Publication.Data.Models.Publication", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("description");

            b.Property<string>("Isbn")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("isbn");

            b.Property<string>("PublicationType")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("publication_type");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("title");

            b.HasKey("Id");

            b.ToTable("publications");
        });

        modelBuilder.Entity("Golden.Publication.Data.Models.PublicationVersion", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("CoverTitle")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("cover_title");

            b.Property<string>("Language")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("language");

            b.Property<Guid>("PublicationGuid")
                .HasColumnType("uuid")
                .HasColumnName("publication_guid");

            b.Property<string>("Version")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("version");

            b.HasKey("Id");

            b.HasIndex("PublicationGuid");

            b.ToTable("publication_versions");
        });

        modelBuilder.Entity("Golden.Publication.Data.Models.PublicationVersion", b =>
        {
            b.HasOne("Golden.Publication.Data.Models.Publication", null)
                .WithMany("Versions")
                .HasForeignKey("PublicationGuid")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Golden.Publication.Data.Models.Publication", b =>
        {
            b.Navigation("Versions");
        });
#pragma warning restore 612, 618
    }
}
